# -*- coding: utf-8 -*-
"""Churn_Find_The_Mistakes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek6-7IhVffCBjFuMtlh2ScrAL77x_jrL

# Customer Churn Prediction – Telco Dataset

**Task:** This notebook was written by a junior analyst. It runs without errors, but it contains **several mistakes** in data handling, modelling, evaluation and interpretation.

Your job:
1. Read and run the notebook.
2. Find every mistake you can. For each one, write: **the cell**, **what is wrong**, **why it matters**, and **how to fix it**.
3. Produce a corrected version of the notebook and compare the results.

Submit your findings as a Word document plus the corrected notebook.

## 1. Load the data
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"
df = pd.read_csv(url)
df.head()

df.info()

"""## 2. Cleaning
`TotalCharges` is stored as text, so we convert it to a number.
"""

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].mean())
df.isnull().sum().sum()

"""## 3. Exploratory analysis"""

churn_by_contract = df.groupby('Contract')['Churn'].apply(lambda s: (s == 'Yes').mean())
churn_by_contract.plot(kind='bar', title='Churn rate by contract type')
plt.ylabel('Churn rate')
plt.show()
churn_by_contract

"""From the chart, **month-to-month customers have the lowest churn rate**, so contract length does not seem to be a strong driver of churn."""

df['Churn'].value_counts()

"""The classes look reasonably balanced, so no special handling is needed.

## 4. Feature engineering
"""

# Churn rate per contract type as a numeric feature
df['contract_churn_rate'] = df['Contract'].map(churn_by_contract)

encoder = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = encoder.fit_transform(df[col])

df.head()

"""## 5. Prepare data for modelling"""

X = df.drop(columns=['Churn'])
y = df['Churn']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2)

"""## 6. Train the model"""

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

"""## 7. Test performance"""

preds = model.predict(X_train)
print("Test accuracy:", accuracy_score(y_train, preds))

"""## 8. Hyperparameter tuning
We try several values of `C` and keep the best one.
"""

best_c, best_acc = None, 0
for c in [0.001, 0.01, 0.1, 1, 10, 100]:
    m = LogisticRegression(C=c, max_iter=1000).fit(X_train, y_train)
    acc = accuracy_score(y_test, m.predict(X_test))
    if acc > best_acc:
        best_c, best_acc = c, acc

print("Best C:", best_c, "| Final test accuracy:", best_acc)

"""## 9. Conclusion

- The model reaches around **80% accuracy**, which is excellent and means it is ready for production.
- Accuracy is the right metric here because the classes are balanced.
- Contract type is not an important factor for churn.
- The final test accuracy above is an unbiased estimate of how the model will perform on new customers.
"""